// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZDpC72en1eUBg34-f-u0rl_HKBF6tr4M',
    appId: '1:119631132083:web:3681c4370fbba05ceac7c6',
    messagingSenderId: '119631132083',
    projectId: 'nexoventapp',
    authDomain: 'nexoventapp.firebaseapp.com',
    storageBucket: 'nexoventapp.appspot.com',
    measurementId: 'G-2TC9NJW4DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI4Ycabbpc5jYltUFy8z_KStooamwskYs',
    appId: '1:119631132083:android:0c5b5928eed9d97ceac7c6',
    messagingSenderId: '119631132083',
    projectId: 'nexoventapp',
    storageBucket: 'nexoventapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZJXDMv8ntOazjxeG2B8_eZ4qwnwiYFGY',
    appId: '1:119631132083:ios:871d01e4e7c731c7eac7c6',
    messagingSenderId: '119631132083',
    projectId: 'nexoventapp',
    storageBucket: 'nexoventapp.appspot.com',
    iosClientId: '119631132083-frdfn445g12oshchbhhlag16d3svu3if.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexoVentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZJXDMv8ntOazjxeG2B8_eZ4qwnwiYFGY',
    appId: '1:119631132083:ios:d049c3663a6d8799eac7c6',
    messagingSenderId: '119631132083',
    projectId: 'nexoventapp',
    storageBucket: 'nexoventapp.appspot.com',
    iosClientId: '119631132083-4j5lc34l08he6gc8urshufr0up33je4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexoVentApp.RunnerTests',
  );
}
